### ISSUE TITLE
Text in header textbox doesn't overflow correctly

### ISSUE THREAD

**Issue by REInVent650** [berdosi/HeartBeat#19]
Maybe introduce a second line or just show pulse?
![InkedScreenshot_20210529-115743_HeartBeat_LI](https://user-images.githubusercontent.com/78056322/120051772-1c653200-c076-11eb-8eb3-32356f0c3a19.jpg)

**Comment by berdosi** [comment]
Thanks!

I'll have a look at it with a line break, and experiment with rescaling the text for smaller device widths.
Removing the second part of the message requires changing all the translations, which I'd avoid.

**Comment by dreamsyntax** [comment]
Expanding on this issue, some devices have issues.
Ex. Pixel 2 XL
![pixel2-xl-UI](https://user-images.githubusercontent.com/14857235/129977245-8d994d80-4142-4dbb-8cf9-948a89ee6710.png)

Will look into making the UI wrap safe

**Comment by dreamsyntax** [comment]
Fixed in v1.3.0
@berdosi issue ready to be closed.

**Comment by berdosi** [comment]
Thanks, closed.
