### ISSUE TITLE
Please provide an APK

### ISSUE THREAD

**Issue by IzzySoft** [berdosi/HeartBeat#2]
Could you please make an APK file available for download? Most projects attach it to the corresponding release (at `releases/`), which would be very fine. Thanks a lot in advance!

**Comment by berdosi** [comment]
Sure, I've added one to [v1.1](https://github.com/berdosi/HeartBeat/releases/tag/v1.1).

**Comment by IzzySoft** [comment]
Thanks a lot! Promotion starts tomorrow around 6 pm UTC [here](https://apt.izzysoft.de/fdroid/index/apk/eu.berdosi.app.heartbeat) and a little later [here](https://android.izzysoft.de/applists/category/named/health_various) :smiley: Will give it a try myself as well. At least one of my devices has camera and flashlight close enough together (the other has them 4cm apart which will make it a bit hard)…

Ah, if you then wish to point to the first location, [here's a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it). I also gladly assist should you want your app listed at [F-Droid.org](https://f-droid.org/) directly.

Until then: All the best, and thanks again!

Oh, PS: future releases will be picked up automatically within 24h of your attaching an APK to a new tag. Description and screenshots are taken along from Fastlane. Users will then automatically be informed that an update is available (if they use my repo with one of the F-Droid clients available). No tracking, no account needed.

**Comment by IzzySoft** [comment]
:rofl: Looks like I missed your MR at F-Droid when asking for the APK – I could just have processed that instead. Done now, so your app will not only show up in my repo tomorrow, but at F-Droid a couple of days later as well. Seeing a new build cycle is just about to start, that could even happen only a day later (see: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client))

So apologies for the confusion!

**Comment by berdosi** [comment]
Thank you so much!

**Comment by IzzySoft** [comment]
Gladly done! And we really made it into the current build cycle (APK [was built already](https://monitor.f-droid.org/builds/log/eu.berdosi.app.heartbeat/2) and should be published within the next few days – with some luck tomorrow night, or shortly thereafter).
