### ISSUE TITLE
New measurement button

### ISSUE THREAD

**Issue by hugh-m** [berdosi/HeartBeat#22]
I am finding Heartbeat very useful. I would like to have a New Measurement button on the main screen, so I could start a new measurement with a single click.

**Comment by berdosi** [comment]
Hello,
apologies for the late reply.
I saw this as something best represented as a [Floating Action Button](https://material.io/components/buttons-floating-action-button), but I was unsure what to do with it while the measurement was in progress – having read the Material UI guidelines, I decided to hide it.
I should be tagging a release soon to have this published.

**Comment by dreamsyntax** [comment]
Confirmed v1.3.0 now has this.
@berdosi issue ready to be closed.

**Comment by berdosi** [comment]
Thanks, closed.
