### ISSUE TITLE
Darkmode Support

### ISSUE THREAD

**Issue by timnea** [berdosi/HeartBeat#9]
i like to see a dark mode feature for the app.

**Comment by berdosi** [comment]
I have a look at it this weekend – it seems okay at first glance, but I might check styling the graph, and see if it indeed switches back to light theme during daytime.
![screenshot-210505-001028](https://user-images.githubusercontent.com/134611/117076429-a69bce00-ad36-11eb-8e98-6ebf8b78e92f.png)

**Comment by timnea** [comment]
Looks good so far but why not make it that it is following the system theme?

**Comment by berdosi** [comment]
Do you mean the accent color one can set in Android 10?
I am not familiar with theming – however, 7675062 removed that weird Material-green from the header.
Dark mode is implemented in #10 now, but I might prefer it to change based on the time of day (which it doesn't).

**Comment by timnea** [comment]
> Do you mean the accent color one can set in Android 10?
> I am not familiar with theming – however, [7675062](https://github.com/berdosi/HeartBeat/commit/7675062f99043a25b8cec848d83488f627ecfab8) removed that weird Material-green from the header.
> Dark mode is implemented in #10 now, but I might prefer it to change based on the time of day (which it doesn't).

in android 10 they added support for dark mode so apps could add an option for choosing for dark or white mode.
https://i.ibb.co/VYH6BSZ/theme-choose.png

**Comment by timnea** [comment]
And second for most people it depends when it's night or day at there place so i recommend an option, rather making it by based on the time of day.

**Comment by berdosi** [comment]
I've got to test it in emulator – #10 lets the app run in dark mode, when the system setting is enabled.
I haven't found the option to change it automatically depending on day/night/environmental light, but I may be unfamiliar with Android 10.
